apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nodify
  namespace: system
  labels:
    app: nodify
spec:
  selector:
    matchLabels:
      app: nodify
  template:
    metadata:
      labels:
        app: nodify
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/os
                    operator: In
                    values:
                      - linux
      securityContext:
        runAsUser: 65532
      hostNetwork: true
      containers:
      - name: daemon
        command:
        - /daemon
        image: daemon:latest
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          limits:
            cpu: 100m
            memory: 30Mi
          requests:
            cpu: 100m
            memory: 20Mi
      terminationGracePeriodSeconds: 10
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoExecute
        operator: Exists
      - effect: NoSchedule
        operator: Exists
