apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- daemon.yaml
generatorOptions:
  disableNameSuffixHash: true
images:
- name: daemon
  newName: nodify-daemon
  newTag: latest
