# permissions for end users to view nodeconditionhandlers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodeconditionhandler-viewer-role
rules:
- apiGroups:
  - azure.microsoft.com
  resources:
  - nodeconditionhandlers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - azure.microsoft.com
  resources:
  - nodeconditionhandlers/status
  verbs:
  - get
