
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - azure.microsoft.com
  resources:
  - nodeconditionhandlers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - azure.microsoft.com
  resources:
  - nodeconditionhandlers/finalizers
  verbs:
  - update
- apiGroups:
  - azure.microsoft.com
  resources:
  - nodeconditionhandlers/status
  verbs:
  - get
  - patch
  - update
