// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeConditionHandler) DeepCopyInto(out *NodeConditionHandler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeConditionHandler.
func (in *NodeConditionHandler) DeepCopy() *NodeConditionHandler {
	if in == nil {
		return nil
	}
	out := new(NodeConditionHandler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeConditionHandler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeConditionHandlerList) DeepCopyInto(out *NodeConditionHandlerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]NodeConditionHandler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeConditionHandlerList.
func (in *NodeConditionHandlerList) DeepCopy() *NodeConditionHandlerList {
	if in == nil {
		return nil
	}
	out := new(NodeConditionHandlerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *NodeConditionHandlerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeConditionHandlerSpec) DeepCopyInto(out *NodeConditionHandlerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeConditionHandlerSpec.
func (in *NodeConditionHandlerSpec) DeepCopy() *NodeConditionHandlerSpec {
	if in == nil {
		return nil
	}
	out := new(NodeConditionHandlerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeConditionHandlerStatus) DeepCopyInto(out *NodeConditionHandlerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeConditionHandlerStatus.
func (in *NodeConditionHandlerStatus) DeepCopy() *NodeConditionHandlerStatus {
	if in == nil {
		return nil
	}
	out := new(NodeConditionHandlerStatus)
	in.DeepCopyInto(out)
	return out
}
