name: build

on:
  push:
    branches:
    - main
    tags:
    - 'v*'
  pull_request:

  workflow_dispatch:

jobs:
  nodify:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'
      - name: GoReleaser Action
        uses: goreleaser/goreleaser-action@v2.4.1
        with:
          install-only: true
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

